export const ADD_USER = 'ADD_USER'
export const SET_USER = 'SET_USER'
export const PRINT_USER = 'PRINT_USER'

export const ADD_PROJECT = 'ADD_PROJECT'
export const SET_PROJECT = 'SET_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const ADD_PROJECTS = 'ADD_PROJECTS'
export const PRINT_PROJECTS = 'PRINT_PROJECTS'
export const SET_ACTIVE_PROJECT_ID = 'SET_ACTIVE_PROJECT_ID'

export const ADD_ISSUES = 'ADD_ISSUES'
export const ADD_ISSUE = 'ADD_ISSUE'
export const SET_ISSUE = 'SET_ISSUE'
export const DELETE_ISSUE = 'DELETE_ISSUE'